### ISSUE TITLE
Restrict system generated audio

### ISSUE THREAD

**Issue by AravindKaay** [OvidijusParsiunas/speech-to-element#1]
Is there a way to restrict system-generated audio like if a youtube video plays on other tab then it needs to restrict that and not to transcribe that as a text

**Comment by OvidijusParsiunas** [comment]
Hey @AravindKaay. This is unfortunately controlled by the providers you are using for speech to text. Most of them just use your microphone input for transcribing text, but I suggest that you could check out their documentation for more information.

Thanks!
