### ISSUE TITLE
Webspeech Options

### ISSUE THREAD

**Issue by 99arp** [OvidijusParsiunas/speech-to-element#3]
Hi. 
As I gathered, this library is used for your other library deep-chat, which I am using. While using webspeech, if one wants to specify custom words that need to be identified, that can be specified using the grammar property. It would be a nice addition to make the stt more flexible. This would just mean adding ` grammars?: string;` [here](https://github.com/OvidijusParsiunas/speech-to-element/blob/7549750cafa505e75448368e896cf3162dc47890/component/src/types/options.ts#L67) and adding initialization logic to the constructor [here](https://github.com/OvidijusParsiunas/speech-to-element/blob/7549750cafa505e75448368e896cf3162dc47890/component/src/services/webSpeech/webSpeech.ts#L44).  Or would you do it differently? 

PS: you have developed a really nice library. Thank you for that.

**Comment by OvidijusParsiunas** [comment]
Hi @99arp, could you elaborate on what you mean by _if one wants to specify custom words that need to be identified, that can be specified using the grammar property_, I don't exactly understand your proposal description.
Could you also provide some examples on what you mean.
Thankyou!

**Comment by OvidijusParsiunas** [comment]
Closed due to no further response from OP.
