### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by GS-BLaszlo** [OvidijusParsiunas/speech-to-element#5]
While using the azure speech recognition we can list some languages and the AI will automatically detect the language.

As I see wee need to use `speechSDK.SpeechRecognizer.FromConfig(...)` factory method instead of `new speechSDK.SpeechRecognizer.FromConfig(speechConfig,  speechSDK.AutoDetectSourceLanguageConfig(...)` constructor at the `component/src/services/azure/azure.js:44` file.
like
```js
const recognizer = speechSDK.SpeechRecognizer.FromConfig(
  speechConfig,  
  speechSDK.AutoDetectSourceLanguageConfig.fromLanguages(
    ["en-US", "ro-RO", "hu-HU", "de-DE"]
  ), 
  audioConfig
);
```

**Comment by GS-BLaszlo** [comment]
i made a [pull request](https://github.com/OvidijusParsiunas/speech-to-element/pull/6/files)

**Comment by OvidijusParsiunas** [comment]
Hi, I have added a few comments to your PR.

If you do not have the time to make them don't worry and I can do it on the main branch myself to get the update out ASAP.

Thankyou for your contribution once again!

**Comment by OvidijusParsiunas** [comment]
Hi, the code has been merged and deployed in `speech-to-element` version `1.0.2`.
Thankyou for your contribution!!
